// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart'
    show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ``
// / `
Future initializeDefaultFirebaseOptions() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNnGVrt04pgnez66PYAOuziIq3ZTOUSIo',
    appId: '1:812669793727:web:301d751949c4758a3cdd0a',
    messagingSenderId: '812669793727',
    projectId: 'notes-f9120',
    authDomain: 'notes-f9120.firebaseapp.com',
    storageBucket: 'notes-f9120.appspot.com',
    measurementId: 'G-5PRGRJNVMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSm2E5Upa89OiFAmwwrwvNR_vcJY2FxGU',
    appId: '1:812669793727:android:759d98c6cd6712ce3cdd0a',
    messagingSenderId: '812669793727',
    projectId: 'notes-f9120',
    storageBucket: 'notes-f9120.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTh-daDWOCpAQgub3JnYc_WxyJadE4pGA',
    appId: '1:812669793727:ios:0b17fcbfb5834a473cdd0a',
    messagingSenderId: '812669793727',
    projectId: 'notes-f9120',
    storageBucket: 'notes-f9120.appspot.com',
    iosClientId:
        '812669793727-upeupg474iugcrka7dsjm2k5c0rabtgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTh-daDWOCpAQgub3JnYc_WxyJadE4pGA',
    appId: '1:812669793727:ios:0b17fcbfb5834a473cdd0a',
    messagingSenderId: '812669793727',
    projectId: 'notes-f9120',
    storageBucket: 'notes-f9120.appspot.com',
    iosClientId:
        '812669793727-upeupg474iugcrka7dsjm2k5c0rabtgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
